#ifndef EVERT_INVERTER_CONF_
#define EVERT_INVERTER_CONF_

#include "inverter_math.h"

#define EVERT_CONSTANT_INVERTER_PWM_PERIOD (27200) // - 1 - 96 // Period - 1 - min

// ADC 1
#define EVERT_CONSTANT_INVERTER_ADC1_CONVERSION_COUNT 9
#define EVERT_CONSTANT_INVERTER_ADC1_RANK_MCU_TEMPERATURE 0 //
#define EVERT_CONSTANT_INVERTER_ADC1_RANK_MCU_VREF_INT 1    //
#define EVERT_CONSTANT_INVERTER_ADC1_RANK_V_BUS 2           // PA0 Channel 1
#define EVERT_CONSTANT_INVERTER_ADC1_RANK_V_BUS_MID 3       // PA1 Channel 2
#define EVERT_CONSTANT_INVERTER_ADC1_RANK_CURRENT_U 4       // PA2 Channel 3
#define EVERT_CONSTANT_INVERTER_ADC1_RANK_CURRENT_V 5       // PC2 Channel 8
#define EVERT_CONSTANT_INVERTER_ADC1_RANK_CURRENT_W 6       // PB1 Channel 12
#define EVERT_CONSTANT_INVERTER_ADC1_RANK_VOLTAGE_U 7       // PB11 Channel 14
#define EVERT_CONSTANT_INVERTER_ADC1_RANK_VOLTAGE_V 8       // PB0 Channel 15

// ADC 2
#define EVERT_CONSTANT_INVERTER_ADC2_CONVERSION_COUNT 5
#define EVERT_CONSTANT_INVERTER_ADC2_RANK_VOLTAGE_W 0      // PA6 Channel 3
#define EVERT_CONSTANT_INVERTER_ADC2_RANK_GRID_VOLTAGE_U 1 // PA7 Channel 4
#define EVERT_CONSTANT_INVERTER_ADC2_RANK_GRID_VOLTAGE_V 2 // PC5 Channel 11
#define EVERT_CONSTANT_INVERTER_ADC2_RANK_GRID_VOLTAGE_W 3 // PB2 Channel 12
#define EVERT_CONSTANT_INVERTER_ADC2_RANK_TEMPERATURE_U 4  // PA4 Channel 17

// ADC 3
#define EVERT_CONSTANT_INVERTER_ADC3_CONVERSION_COUNT 9
#define EVERT_CONSTANT_INVERTER_ADC3_RANK_TEMPERATURE_V 0    // PE9 Channel 2
#define EVERT_CONSTANT_INVERTER_ADC3_RANK_TEMPERATURE_W 1    // PE13 Channel 3
#define EVERT_CONSTANT_INVERTER_ADC3_RESERVE_FILTER_TEMP_U 2 // PE8 Channel 6
#define EVERT_CONSTANT_INVERTER_ADC3_RESERVE_FILTER_TEMP_V 3 // PD10 Channel 7
#define EVERT_CONSTANT_INVERTER_ADC3_RESERVE_FILTER_TEMP_W 4 // PD11 Channel 8
#define EVERT_CONSTANT_INVERTER_ADC3_TEMP_AMBIENT 5          // PD13 Channel 10
#define EVERT_CONSTANT_INVERTER_ADC3_RESERVE_2 6             // PE10 Channel 14
#define EVERT_CONSTANT_INVERTER_ADC3_RESERVE_3 7             // PE11 Channel 15
#define EVERT_CONSTANT_INVERTER_ADC3_RESERVE_4 8             // PE12 Channel 16

// Calibrations
#define EVERT_CALIBRATION_INV_ADC_VOLTAGE_BUS_SLOPE 0.31609195f
#define EVERT_CALIBRATION_INV_ADC_VOLTAGE_BUS_INTERCEPT -0.0804598f
#define EVERT_CALIBRATION_INV_ADC_VOLTAGE_BUS_MIDDLE_SLOPE 0.16216216f
#define EVERT_CALIBRATION_INV_ADC_VOLTAGE_BUS_MIDDLE_INTERCEPT -0.5810811f
#define EVERT_CALIBRATION_INV_ADC_VOLTAGE_U_SLOPE 0.16278487f
#define EVERT_CALIBRATION_INV_ADC_VOLTAGE_U_INTERCEPT -341.60406f
#define EVERT_CALIBRATION_INV_ADC_VOLTAGE_V_SLOPE 0.16278487f
#define EVERT_CALIBRATION_INV_ADC_VOLTAGE_V_INTERCEPT -341.60406f
#define EVERT_CALIBRATION_INV_ADC_VOLTAGE_W_SLOPE 0.16278487f
#define EVERT_CALIBRATION_INV_ADC_VOLTAGE_W_INTERCEPT -341.60406f
#define EVERT_CALIBRATION_INV_ADC_VOLTAGE_GRID_U_SLOPE 0.16278487f
#define EVERT_CALIBRATION_INV_ADC_VOLTAGE_GRID_U_INTERCEPT -341.60406f
#define EVERT_CALIBRATION_INV_ADC_VOLTAGE_GRID_V_SLOPE 0.16278487f
#define EVERT_CALIBRATION_INV_ADC_VOLTAGE_GRID_V_INTERCEPT -341.60406f
#define EVERT_CALIBRATION_INV_ADC_VOLTAGE_GRID_W_SLOPE 0.16278487f
#define EVERT_CALIBRATION_INV_ADC_VOLTAGE_GRID_W_INTERCEPT -341.60406f
#define EVERT_CALIBRATION_INV_ADC_CURRENT_U_SLOPE 0.004884f
#define EVERT_CALIBRATION_INV_ADC_CURRENT_U_INTERCEPT -10.0f
#define EVERT_CALIBRATION_INV_ADC_CURRENT_V_SLOPE 0.004884f
#define EVERT_CALIBRATION_INV_ADC_CURRENT_V_INTERCEPT -10.0f
#define EVERT_CALIBRATION_INV_ADC_CURRENT_W_SLOPE 0.004884f
#define EVERT_CALIBRATION_INV_ADC_CURRENT_W_INTERCEPT -10.0f
#define EVERT_CALIBRATION_INV_ADC_TEMPERATURE_HEATSINK_U_SLOPE 0.02442002f
#define EVERT_CALIBRATION_INV_ADC_TEMPERATURE_HEATSINK_U_INTERCEPT 0.0f
#define EVERT_CALIBRATION_INV_ADC_TEMPERATURE_HEATSINK_V_SLOPE 0.02442002f
#define EVERT_CALIBRATION_INV_ADC_TEMPERATURE_HEATSINK_V_INTERCEPT 0.0f
#define EVERT_CALIBRATION_INV_ADC_TEMPERATURE_HEATSINK_W_SLOPE 0.02442002f
#define EVERT_CALIBRATION_INV_ADC_TEMPERATURE_HEATSINK_W_INTERCEPT 0.0f
#define EVERT_CALIBRATION_INV_ADC_TEMPERATURE_FILTER_COIL_U_SLOPE 0.02442002f
#define EVERT_CALIBRATION_INV_ADC_TEMPERATURE_FILTER_COIL_U_INTERCEPT 0.0f
#define EVERT_CALIBRATION_INV_ADC_TEMPERATURE_FILTER_COIL_V_SLOPE 0.02442002f
#define EVERT_CALIBRATION_INV_ADC_TEMPERATURE_FILTER_COIL_V_INTERCEPT 0.0f
#define EVERT_CALIBRATION_INV_ADC_TEMPERATURE_FILTER_COIL_W_SLOPE 0.02442002f
#define EVERT_CALIBRATION_INV_ADC_TEMPERATURE_FILTER_COIL_W_INTERCEPT 0.0f
#define EVERT_CALIBRATION_INV_ADC_TEMPERATURE_AMBIENT_SLOPE (-0.058843432f)
#define EVERT_CALIBRATION_INV_ADC_TEMPERATURE_AMBIENT_INTERCEPT (189.2844104f)

// STATUS LEDS
//
//     / --
//    /
//   /    / --
//  /    /
// [1] [0]
// _______
// [     ]
// [ MCU ]
// [     ]

#define EVERT_CONSTANT_INVERTER_STATUS_LED0_COLOR_BOOTING ((uint32_t)(EVERT_FZ2812_RGB_TO_GRB(0x0000FF)))
#define EVERT_CONSTANT_INVERTER_STATUS_LED0_COLOR_OK ((uint32_t)(EVERT_FZ2812_RGB_TO_GRB(0x00FF00)))
#define EVERT_CONSTANT_INVERTER_STATUS_LED0_COLOR_WARNING ((uint32_t)(EVERT_FZ2812_RGB_TO_GRB(0xFFFF00)))
#define EVERT_CONSTANT_INVERTER_STATUS_LED0_COLOR_ERROR ((uint32_t)(EVERT_FZ2812_RGB_TO_GRB(0xFF0000)))
#define EVERT_CONSTANT_INVERTER_STATUS_LED0_TIME_BOOTING_ON (200)
#define EVERT_CONSTANT_INVERTER_STATUS_LED0_TIME_BOOTING_OFF (200)
#define EVERT_CONSTANT_INVERTER_STATUS_LED0_TIME_OK_ON (1000)
#define EVERT_CONSTANT_INVERTER_STATUS_LED0_TIME_OK_OFF (200)
#define EVERT_CONSTANT_INVERTER_STATUS_LED0_TIME_WARNING_ON (500)
#define EVERT_CONSTANT_INVERTER_STATUS_LED0_TIME_WARNING_OFF (500)
#define EVERT_CONSTANT_INVERTER_STATUS_LED0_TIME_ERROR_ON (0)
#define EVERT_CONSTANT_INVERTER_STATUS_LED0_TIME_ERROR_OFF (0)

#define EVERT_CONSTANT_INVERTER_STATUS_LED1_COLOR_BOOTING (EVERT_FZ2812_RGB_TO_GRB(0x0000FF))
#define EVERT_CONSTANT_INVERTER_STATUS_LED1_COLOR_OK (EVERT_FZ2812_RGB_TO_GRB(0x00FF00))
#define EVERT_CONSTANT_INVERTER_STATUS_LED1_COLOR_WARNING (EVERT_FZ2812_RGB_TO_GRB(0xFFFF00))
#define EVERT_CONSTANT_INVERTER_STATUS_LED1_COLOR_ERROR (EVERT_FZ2812_RGB_TO_GRB(0xFF0000))
#define EVERT_CONSTANT_INVERTER_STATUS_LED1_TIME_BOOTING_ON (200)
#define EVERT_CONSTANT_INVERTER_STATUS_LED1_TIME_BOOTING_OFF (200)
#define EVERT_CONSTANT_INVERTER_STATUS_LED1_TIME_OK_ON (1000)
#define EVERT_CONSTANT_INVERTER_STATUS_LED1_TIME_OK_OFF (200)
#define EVERT_CONSTANT_INVERTER_STATUS_LED1_TIME_WARNING_ON (500)
#define EVERT_CONSTANT_INVERTER_STATUS_LED1_TIME_WARNING_OFF (500)
#define EVERT_CONSTANT_INVERTER_STATUS_LED1_TIME_ERROR_ON (0)
#define EVERT_CONSTANT_INVERTER_STATUS_LED1_TIME_ERROR_OFF (0)

// Grid Forming
#define EVERT_CONSTANT_INVERTER_L_INDUCTOR_VALUE ((float32_t)(0.000340f))
#define EVERT_SETTING_INVERTER_CURRENT_RMS_MAX ((float32_t)(10.0f))
#define EVERT_SETTING_INVERTER_CURRENT_INSTANTANEOUS_MAX ((float32_t)(EVERT_SETTING_INVERTER_CURRENT_RMS_MAX * M_SQRT2))
#define EVERT_SETTING_INVERTER_VOLTAGE_BUS_NOMINAL ((float32_t)(800.0f))
#define EVERT_SETTING_INVERTER_VOLTAGE_BUS_MID_NOMINAL ((float32_t)(EVERT_SETTING_INVERTER_VOLTAGE_BUS_NOMINAL / 2.0f))
#define EVERT_SETTING_INVERTER_VOLTAGE_BUS_MAX ((float32_t)(950.0f))
#define EVERT_SETTING_INVERTER_VOLTAGE_BUS_MIN ((float32_t)(650.0f))
#define EVERT_SETTING_INVERTER_GRID_NOMINAL_FREQUENCY ((float32_t)(50.0f))
#define EVERT_SETTING_INVERTER_GRID_NOMINAL_FREQUENCY_DEVIATION ((float32_t)(5.0f)) // +- 5Hz
#define EVERT_SETTING_INVERTER_VOLTAGE_RMS_NOMINAL ((float32_t)(230.0f))
#define EVERT_SETTING_INVERTER_VOLTAGE_RMS_MAX ((float32_t)(EVERT_SETTING_INVERTER_VOLTAGE_RMS_NOMINAL * 1.05f))
#define EVERT_SETTING_INVERTER_VOLTAGE_RMS_MIN ((float32_t)(EVERT_SETTING_INVERTER_VOLTAGE_RMS_NOMINAL - (EVERT_SETTING_INVERTER_VOLTAGE_RMS_NOMINAL * 1.1f)))
#define EVERT_SETTING_INVERTER_VOLTAGE_INSTANTANEOUS_MAX ((float32_t)(EVERT_SETTING_INVERTER_VOLTAGE_RMS_MAX * M_SQRT2))
#define EVERT_SETTING_INVERTER_VOLTAGE_INSTANTANEOUS_MIN ((float32_t)(-EVERT_SETTING_INVERTER_VOLTAGE_INSTANTANEOUS_MAX))
#define EVERT_SETTING_INVERTER_PLL_DECOUPLING_FACTOR ((float32_t)(2.0f * M_PI * EVERT_CONSTANT_INVERTER_L_INDUCTOR_VALUE * EVERT_SETTING_INVERTER_CURRENT_INSTANTANEOUS_MAX / EVERT_SETTING_INVERTER_VOLTAGE_BUS_MAX))

#endif // EVERT_INVERTER_CONF_