EVERT
EVERT_CAN_FifoStatusTypeDef
EVERT_CAN_ProcessBufferStatusTypeDef
EVERT_CAN_MessageIdTypeDef EVERT_CAN_IdentifierTypeDef::message_id
Referenced by EVERT_CAN_Identifier_CreateNew, EVERT_CAN_Identifier_FromUint32, EVERT_CAN_Identifier_SetMessageId, EVERT_CAN_Identifier_ToUint32.
EVERT_CAN_DeviceIdentifierTypeDef EVERT_CAN_IdentifierTypeDef::source_id
Referenced by EVERT_CAN_Identifier_CreateNew, EVERT_CAN_Identifier_FromUint32, EVERT_CAN_Identifier_SetSourceId, EVERT_CAN_Identifier_ToUint32.
EVERT_CAN_DeviceIdentifierTypeDef EVERT_CAN_IdentifierTypeDef::target_id
Referenced by EVERT_CAN_Identifier_CreateNew, EVERT_CAN_Identifier_FromUint32, EVERT_CAN_Identifier_SetTargetId, EVERT_CAN_Identifier_ToUint32.
uint8_t EVERT_CAN_IdentifierTypeDef::evert_flag
Referenced by EVERT_CAN_Identifier_CreateNew, EVERT_CAN_Identifier_FromUint32, EVERT_CAN_Identifier_ToUint32.
EVERT_CAN_MessagePriorityTypeDef EVERT_CAN_IdentifierTypeDef::priority
Referenced by EVERT_CAN_Identifier_CreateNew, EVERT_CAN_Identifier_FromUint32, EVERT_CAN_Identifier_SetPriority, EVERT_CAN_Identifier_ToUint32.
uint16_t EVERT_CAN_IdentifierTypeDef::zero_padding
Referenced by EVERT_CAN_Identifier_FromUint32.
uint8_t EVERT_CAN_FrameDataTypeDef::length
Referenced by __attribute__, EVERT_CAN_Frame_Copy, EVERT_CAN_Frame_CreateNew, EVERT_CAN_Handler_ProcessTxBuffer, EVERT_CAN_Handler_Receive.
uint8_t EVERT_CAN_FrameDataTypeDef::data[7][7]
Referenced by __attribute__, EVERT_CAN_Frame_Copy, EVERT_CAN_Frame_CreateNew, EVERT_CAN_Handler_ProcessTxBuffer, EVERT_CAN_Handler_Receive.
EVERT_CAN_IdentifierTypeDef EVERT_CAN_FrameTypeDef::identifier
Referenced by EVERT_CAN_Frame_Copy, EVERT_CAN_Frame_CreateNew, EVERT_CAN_Frame_SetIdentifier, EVERT_CAN_Handler_ProcessTxBuffer, EVERT_CAN_Handler_Receive.
EVERT_CAN_FrameDataTypeDef EVERT_CAN_FrameTypeDef::data
Referenced by __attribute__, EVERT_CAN_Frame_Copy, EVERT_CAN_Frame_CreateNew, EVERT_CAN_Handler_ProcessTxBuffer, EVERT_CAN_Handler_Receive.
EVERT_CAN_FrameTypeDef EVERT_CAN_FifoBufferItemTypeDef::frame
Referenced by EVERT_CAN_FifoBuffer_Pop, EVERT_CAN_FifoBuffer_Push.
EVERT_CAN_FifoBufferItemTypeDef* EVERT_CAN_FifoBufferTypeDef::buffer
Referenced by EVERT_CAN_FifoBuffer_Init, EVERT_CAN_FifoBuffer_Pop, EVERT_CAN_FifoBuffer_Push.
uint32_t EVERT_CAN_FifoBufferTypeDef::head
Referenced by EVERT_CAN_FifoBuffer_Init, EVERT_CAN_FifoBuffer_Push.
uint32_t EVERT_CAN_FifoBufferTypeDef::tail
Referenced by EVERT_CAN_FifoBuffer_Init, EVERT_CAN_FifoBuffer_Pop.
uint32_t EVERT_CAN_FifoBufferTypeDef::size
Referenced by EVERT_CAN_FifoBuffer_Init, EVERT_CAN_FifoBuffer_Pop, EVERT_CAN_FifoBuffer_Push.
uint32_t EVERT_CAN_FifoBufferTypeDef::count
Referenced by EVERT_CAN_FifoBuffer_Init, EVERT_CAN_FifoBuffer_Pop, EVERT_CAN_FifoBuffer_Push.
void(* EVERT_CAN_HandlerTypeDef::OnErrorReceived) (void))(void)
Referenced by EVERT_CAN_OnErrorReceived.
void(* EVERT_CAN_HandlerTypeDef::OnMessageReceived) (const EVERT_CAN_FrameTypeDef frame))(const EVERT_CAN_FrameTypeDef frame)
Referenced by EVERT_CAN_OnMessageReceived.
void(* EVERT_CAN_HandlerTypeDef::OnMessageTransmitted) (const EVERT_CAN_FrameTypeDef frame))(const EVERT_CAN_FrameTypeDef frame)
Referenced by EVERT_CAN_OnMessageTransmitted.
FDCAN_HandleTypeDef* EVERT_CAN_HandlerTypeDef::hfdcan
Referenced by EVERT_CAN_Handler_Init, EVERT_CAN_Handler_ProcessTxBuffer, EVERT_CAN_Handler_Receive.
EVERT_CAN_IdentifierTypeDef EVERT_CAN_HandlerTypeDef::identifier
Referenced by EVERT_CAN_Handler_Init, EVERT_CAN_Handler_Transmit.
EVERT_CAN_FifoBufferTypeDef EVERT_CAN_HandlerTypeDef::rx_fifo_buffer
Referenced by EVERT_CAN_Handler_Init, EVERT_CAN_Handler_ProcessRxBuffer, EVERT_CAN_Handler_Receive.
EVERT_CAN_FifoBufferTypeDef EVERT_CAN_HandlerTypeDef::tx_fifo_buffer
Referenced by EVERT_CAN_Handler_Init, EVERT_CAN_Handler_ProcessTxBuffer, EVERT_CAN_Handler_Transmit.
FDCAN_RxHeaderTypeDef EVERT_CAN_HandlerTypeDef::rx_header
Referenced by EVERT_CAN_Handler_Receive.
FDCAN_TxHeaderTypeDef EVERT_CAN_HandlerTypeDef::tx_header
Referenced by EVERT_CAN_Handler_Init, EVERT_CAN_Handler_ProcessTxBuffer.
uint8_t EVERT_CAN_HandlerTypeDef::rx_data[8][8]
Referenced by EVERT_CAN_Handler_Receive.
uint8_t EVERT_CAN_HandlerTypeDef::tx_data[8][8]
Referenced by EVERT_CAN_Handler_ProcessTxBuffer.
EVERT_CAN_ProcessBufferStatusTypeDef EVERT_CAN_HandlerTypeDef::rx_status
Referenced by EVERT_CAN_Handler_ProcessRxBuffer.
EVERT_CAN_ProcessBufferStatusTypeDef EVERT_CAN_HandlerTypeDef::tx_status
Referenced by EVERT_CAN_Handler_ProcessTxBuffer.
void EVERT_CAN_Identifier_CreateNew(EVERT_CAN_IdentifierTypeDef *identifier)
References CAN_MESSAGE_PRIORITY_NORMAL, EVERT_CAN_IdentifierTypeDef::evert_flag, EVERT_CAN_IdentifierTypeDef::message_id, EVERT_CAN_IdentifierTypeDef::priority, EVERT_CAN_IdentifierTypeDef::source_id, EVERT_CAN_IdentifierTypeDef::target_id.
Referenced by EVERT_CAN_Frame_CreateNew, EVERT_CAN_Handler_Init.
void EVERT_CAN_Identifier_SetMessageId(EVERT_CAN_IdentifierTypeDef *identifier, EVERT_CAN_MessageIdTypeDef message_id)
References EVERT_CAN_IdentifierTypeDef::message_id.
void EVERT_CAN_Identifier_SetSourceId(EVERT_CAN_IdentifierTypeDef *identifier, EVERT_CAN_DeviceIdentifierTypeDef source_id)
References EVERT_CAN_IdentifierTypeDef::source_id.
Referenced by EVERT_CAN_Handler_Init.
void EVERT_CAN_Identifier_SetTargetId(EVERT_CAN_IdentifierTypeDef *identifier, EVERT_CAN_DeviceIdentifierTypeDef target_id)
References EVERT_CAN_IdentifierTypeDef::target_id.
void EVERT_CAN_Identifier_SetPriority(EVERT_CAN_IdentifierTypeDef *identifier, EVERT_CAN_MessagePriorityTypeDef priority)
References EVERT_CAN_IdentifierTypeDef::priority.
void EVERT_CAN_Identifier_FromUint32(uint32_t id, EVERT_CAN_IdentifierTypeDef *identifier)
References EVERT_CAN_IdentifierTypeDef::evert_flag, EVERT_CAN_IdentifierTypeDef::message_id, EVERT_CAN_IdentifierTypeDef::priority, EVERT_CAN_IdentifierTypeDef::source_id, EVERT_CAN_IdentifierTypeDef::target_id, EVERT_CAN_IdentifierTypeDef::zero_padding.
Referenced by EVERT_CAN_Handler_Receive.
void EVERT_CAN_Identifier_ToUint32(EVERT_CAN_IdentifierTypeDef *identifier, uint32_t *id)
References EVERT_CAN_IdentifierTypeDef::evert_flag, EVERT_CAN_IdentifierTypeDef::message_id, EVERT_CAN_IdentifierTypeDef::priority, EVERT_CAN_IdentifierTypeDef::source_id, EVERT_CAN_IdentifierTypeDef::target_id.
Referenced by EVERT_CAN_Handler_ProcessTxBuffer.
void EVERT_CAN_Frame_CreateNew(EVERT_CAN_FrameTypeDef *frame)
References EVERT_CAN_FrameDataTypeDef::data, EVERT_CAN_FrameTypeDef::data, EVERT_CAN_Identifier_CreateNew, EVERT_CAN_FrameTypeDef::identifier, EVERT_CAN_FrameDataTypeDef::length.
Referenced by EVERT_CAN_Handler_ProcessTxBuffer, EVERT_CAN_Handler_Transmit.
void EVERT_CAN_Frame_Copy(EVERT_CAN_FrameTypeDef *frame, EVERT_CAN_FrameTypeDef *frame_copy)
References EVERT_CAN_FrameDataTypeDef::data, EVERT_CAN_FrameTypeDef::data, EVERT_CAN_FrameTypeDef::identifier, EVERT_CAN_FrameDataTypeDef::length.
void EVERT_CAN_Frame_SetData(EVERT_CAN_FrameTypeDef *frame, const uint8_t length, const uint8_t *message)
Referenced by EVERT_CAN_Handler_Transmit.
void EVERT_CAN_Frame_SetIdentifier(EVERT_CAN_FrameTypeDef *frame, const EVERT_CAN_IdentifierTypeDef identifier)
References EVERT_CAN_FrameTypeDef::identifier.
Referenced by EVERT_CAN_Handler_Transmit.
void EVERT_CAN_FifoBuffer_Init(EVERT_CAN_FifoBufferTypeDef *buffer, EVERT_CAN_FifoBufferItemTypeDef *buffer_items, uint32_t size)
References EVERT_CAN_FifoBufferTypeDef::buffer, EVERT_CAN_FifoBufferTypeDef::count, EVERT_CAN_FifoBufferTypeDef::head, EVERT_CAN_FifoBufferTypeDef::size, EVERT_CAN_FifoBufferTypeDef::tail.
Referenced by EVERT_CAN_Handler_Init.
EVERT_CAN_FifoStatusTypeDef EVERT_CAN_FifoBuffer_Push(EVERT_CAN_FifoBufferTypeDef *buffer, const EVERT_CAN_FrameTypeDef frame)
References EVERT_CAN_FifoBufferTypeDef::buffer, CAN_FS_FULL, CAN_FS_OK, EVERT_CAN_FifoBufferTypeDef::count, EVERT_CAN_FifoBufferItemTypeDef::frame, EVERT_CAN_FifoBufferTypeDef::head, EVERT_CAN_FifoBufferTypeDef::size.
Referenced by EVERT_CAN_Handler_Receive, EVERT_CAN_Handler_Transmit.
EVERT_CAN_FifoStatusTypeDef EVERT_CAN_FifoBuffer_Pop(EVERT_CAN_FifoBufferTypeDef *buffer, EVERT_CAN_FrameTypeDef *frame)
References EVERT_CAN_FifoBufferTypeDef::buffer, CAN_FS_EMPTY, CAN_FS_OK, EVERT_CAN_FifoBufferTypeDef::count, EVERT_CAN_FifoBufferItemTypeDef::frame, EVERT_CAN_FifoBufferTypeDef::size, EVERT_CAN_FifoBufferTypeDef::tail.
Referenced by EVERT_CAN_Handler_ProcessRxBuffer, EVERT_CAN_Handler_ProcessTxBuffer.
HAL_StatusTypeDef EVERT_CAN_Handler_Init(FDCAN_HandleTypeDef *hfdcan, EVERT_CAN_HandlerTypeDef *handler, EVERT_CAN_DeviceIdentifierTypeDef device_id, EVERT_CAN_FifoBufferItemTypeDef *rx_fifo_items, EVERT_CAN_FifoBufferItemTypeDef *tx_fifo_items, uint32_t size)
References EVERT_CAN_FifoBuffer_Init, EVERT_CAN_Identifier_CreateNew, EVERT_CAN_Identifier_SetSourceId, EVERT_CAN_HandlerTypeDef::hfdcan, EVERT_CAN_HandlerTypeDef::identifier, EVERT_CAN_HandlerTypeDef::rx_fifo_buffer, EVERT_CAN_HandlerTypeDef::tx_fifo_buffer, EVERT_CAN_HandlerTypeDef::tx_header.
EVERT_CAN_FifoStatusTypeDef EVERT_CAN_Handler_Receive(EVERT_CAN_HandlerTypeDef *handler, const uint32_t RxFifo0ITs)
References CAN_FS_ERROR, CAN_FS_OK, EVERT_CAN_FrameDataTypeDef::data, EVERT_CAN_FrameTypeDef::data, EVERT_CAN_FifoBuffer_Push, EVERT_CAN_Identifier_FromUint32, EVERT_CAN_OnErrorReceived, EVERT_CAN_HandlerTypeDef::hfdcan, EVERT_CAN_FrameTypeDef::identifier, EVERT_CAN_FrameDataTypeDef::length, EVERT_CAN_HandlerTypeDef::rx_data, EVERT_CAN_HandlerTypeDef::rx_fifo_buffer, EVERT_CAN_HandlerTypeDef::rx_header.
EVERT_CAN_FifoStatusTypeDef EVERT_CAN_Handler_Transmit(EVERT_CAN_HandlerTypeDef *handler, const uint8_t length, const uint8_t *message)
References EVERT_CAN_FifoBuffer_Push, EVERT_CAN_Frame_CreateNew, EVERT_CAN_Frame_SetData, EVERT_CAN_Frame_SetIdentifier, EVERT_CAN_HandlerTypeDef::identifier, EVERT_CAN_HandlerTypeDef::tx_fifo_buffer.
EVERT_CAN_ProcessBufferStatusTypeDef EVERT_CAN_Handler_ProcessRxBuffer(EVERT_CAN_HandlerTypeDef *handler)
References CAN_FS_OK, CAN_PBS_IDLE, CAN_PBS_PROCESSING_RECEIVED_DATA, EVERT_CAN_FifoBuffer_Pop, EVERT_CAN_OnMessageReceived, EVERT_CAN_HandlerTypeDef::rx_fifo_buffer, EVERT_CAN_HandlerTypeDef::rx_status.
EVERT_CAN_ProcessBufferStatusTypeDef EVERT_CAN_Handler_ProcessTxBuffer(EVERT_CAN_HandlerTypeDef *handler)
References CAN_FS_OK, CAN_PBS_IDLE, CAN_PBS_OK, CAN_PBS_WAITING_FOR_INTERNAL_BUFFER, EVERT_CAN_FrameDataTypeDef::data, EVERT_CAN_FrameTypeDef::data, EVERT_CAN_FifoBuffer_Pop, EVERT_CAN_Frame_CreateNew, EVERT_CAN_Identifier_ToUint32, EVERT_CAN_OnMessageTransmitted, EVERT_CAN_HandlerTypeDef::hfdcan, EVERT_CAN_FrameTypeDef::identifier, EVERT_CAN_FrameDataTypeDef::length, EVERT_CAN_HandlerTypeDef::tx_data, EVERT_CAN_HandlerTypeDef::tx_fifo_buffer, EVERT_CAN_HandlerTypeDef::tx_header, EVERT_CAN_HandlerTypeDef::tx_status.
void EVERT_CAN_OnErrorReceived(EVERT_CAN_HandlerTypeDef *handler)
References EVERT_CAN_HandlerTypeDef::OnErrorReceived.
Referenced by EVERT_CAN_Handler_Receive.
void EVERT_CAN_OnMessageReceived(EVERT_CAN_HandlerTypeDef *handler, const EVERT_CAN_FrameTypeDef frame)
References EVERT_CAN_HandlerTypeDef::OnMessageReceived.
Referenced by EVERT_CAN_Handler_ProcessRxBuffer.
void EVERT_CAN_OnMessageTransmitted(EVERT_CAN_HandlerTypeDef *handler, const EVERT_CAN_FrameTypeDef frame)
References EVERT_CAN_HandlerTypeDef::OnMessageTransmitted.
Referenced by EVERT_CAN_Handler_ProcessTxBuffer.