// This file was generated by the 'c' protocol generator.
// Source-of-truth:
//     https://github.com/kureono/evert-protocols/sot/src/Evert.Protocols.Can/DeviceAlarmRegister1Index.cs
// Protocol-repo:
//     https://github.com/kureono/evert-protocols-c
// Created:
//     31/10/2024 10:23:57
// ! Do not modify this file directly. !

#ifndef EVERT_DEVICE_ALARM_REGISTER1_INDEX_H_
#define EVERT_DEVICE_ALARM_REGISTER1_INDEX_H_

typedef enum
{
    DARI_BOOT_SELFTEST = 0,
    DARI_HAL_ERROR = 1,
    DARI_HAL_CAN_ERROR = 2,
    DARI_HAL_ADC_OVERRUN = 3,
    DARI_HAL_ADC_ERROR = 4,
    DARI_HAL_DMA_ERROR = 5,
    DARI_HAL_FLASH_ERROR = 6,
    DARI_HAL_I2C_ERROR = 7,
    DARI_HAL_TIM_ERROR = 8,
    DARI_HAL_UART_ERROR = 9,
    DARI_ISR1_CYCLES = 10,
    DARI_ISR2_CYCLES = 11,
    DARI_CPU_OVERTEMPERATURE_CRITICAL = 12,
    DARI_CPU_OVERTEMPERATURE_WARNING = 13,
    DARI_CPU_UNDERTEMPERATURE_WARNING = 14,
    DARI_CPU_UNDERTEMPERATURE_CRITICAL = 15,
    DARI_CPU_OVERVOLTAGE_CRITICAL = 16,
    DARI_CPU_OVERVOLTAGE_WARNING = 17,
    DARI_CPU_UNDERVOLTAGE_WARNING = 18,
    DARI_CPU_UNDERVOLTAGE_CRITICAL = 19,
    DARI_CRITICAL_COMMS = 20,
} EVERT_DEVICE_AlarmRegister1IndexTypeDef;

#endif // EVERT_DEVICE_ALARM_REGISTER1_INDEX_H_
