// This file was generated by the 'c' protocol generator.
// Source-of-truth:
//     https://github.com/kureono/evert-protocols/sot/src/Evert.Protocols.Can/DeviceState.cs
// Protocol-repo:
//     https://github.com/kureono/evert-protocols-c
// Created:
//     31/10/2024 10:23:57
// ! Do not modify this file directly. !

#ifndef EVERT_DEVICE_STATE_H_
#define EVERT_DEVICE_STATE_H_

typedef enum
{
    DS_UNKNOWN = 0,
    DS_BOOTING = 1,
    DS_BOOTING_ADC = 2,
    DS_BOOTING_COMMS = 3,
    DS_BOOTING_DONE = 4,
    DS_HANDSHAKE_ANNOUNCING = 5,
    DS_HANDSHAKE_ACKNOWLEDGED = 6,
    DS_OPERATIONAL = 7,
    DS_OPERATIONAL_WARNING = 8,
    DS_NON_OPERATIONAL = 9,
    DS_EMERGENCY_SHUTDOWN = 10,
} EVERT_DEVICE_StateTypeDef;

#endif // EVERT_DEVICE_STATE_H_
