// This file was generated by the 'c' protocol generator.
// Source-of-truth:
//     https://github.com/kureono/evert-protocols/sot/src/Evert.Protocols.Can/DeviceVersionInfo.cs
// Protocol-repo:
//     https://github.com/kureono/evert-protocols-c
// Created:
//     31/10/2024 10:23:57
// ! Do not modify this file directly. !

#ifndef EVERT_DEVICE_VERSION_INFO_H_
#define EVERT_DEVICE_VERSION_INFO_H_

#include <stdint.h>

#pragma pack(push, 1)

// Total Size: 3B
typedef struct
{
    uint8_t major; // Size: 1B
    uint8_t minor; // Size: 1B
    uint8_t patch; // Size: 1B
} EVERT_DEVICE_VersionInfoTypeDef;

#pragma pack(pop)

#endif // EVERT_DEVICE_VERSION_INFO_H_
