// This file was generated by the 'c' protocol generator.
// Source-of-truth:
//     https://github.com/kureono/evert-protocols/sot/src/Evert.Protocols.Can/DeviceMode.cs
// Protocol-repo:
//     https://github.com/kureono/evert-protocols-c
// Created:
//     31/10/2024 10:23:57
// ! Do not modify this file directly. !

#ifndef EVERT_DEVICE_MODE_H_
#define EVERT_DEVICE_MODE_H_

typedef enum
{
    DM_MANUAL = 0,
    DM_AUTOMATIC = 1,
} EVERT_DEVICE_ModeTypeDef;

#endif // EVERT_DEVICE_MODE_H_
