emc230x.h
EMC230X_ADDRESS
EMC2303_REG_CONFIG_RANGE_500
EMC2303_REG_CONFIG_RANGE_1000
EMC2303_REG_CONFIG_RANGE_2000
EMC2303_REG_CONFIG_RANGE_4000
EMC2303_REG_CONFIG_RANGE_MASK
EMC2303_REG_CONFIG_RANGE_500_M
EMC2303_REG_CONFIG_RANGE_1000_M
EMC2303_REG_CONFIG_RANGE_2000_M
EMC2303_REG_CONFIG_RANGE_4000_M
EMC230X_REG_FAN1_BASE
EMC230X_REG_FAN2_BASE
EMC230X_REG_FAN3_BASE
EMC230X_GET_REGISTER
EMC230X_REG_FANX_SETTING
EMC230X_REG_FANX_CONFIGURATION1
EMC230X_REG_FANX_CONFIGURATION2
EMC230X_REG_FANX_TACH_HIGH
EMC230X_REG_FANX_TACH_LOW
EMC230X_REG_FAN1_SETTING
EMC230X_REG_FAN1_CONFIGURATION1
EMC230X_REG_FAN1_CONFIGURATION2
EMC230X_REG_FAN1_TACH_HIGH
EMC230X_REG_FAN1_TACH_LOW
EMC230X_REG_FAN2_SETTING
EMC230X_REG_FAN2_CONFIGURATION1
EMC230X_REG_FAN2_CONFIGURATION2
EMC230X_REG_FAN2_TACH_HIGH
EMC230X_REG_FAN2_TACH_LOW
EMC230X_REG_FAN3_SETTING
EMC230X_REG_FAN3_CONFIGURATION1
EMC230X_REG_FAN3_CONFIGURATION2
EMC230X_REG_FAN3_TACH_HIGH
EMC230X_REG_FAN3_TACH_LOW
EVERT_EMC230X_Fan
EVERT_EMC230X_RxAction
EVERT_EMC230X_TxAction
I2C_HandleTypeDef hi2c1
Referenced by EVERT_EMC230X_ReadTachs_IT, EVERT_EMC230X_SetAllFanSpeeds_IT, EVERT_EMC230X_SetFanSpeed_IT.
void EVERT_EMC230X_Init()
References EMC2303_REG_CONFIG_RANGE_1000, EVERT_EMC230X_RX_ACTION_NONE, EVERT_EMC230X_SetRangeRegister_IT, EVERT_EMC230X_SetRxAction, EVERT_EMC230X_SetTxAction, EVERT_EMC230X_TX_ACTION_NONE.
void EVERT_EMC230X_SetAllFanSpeeds_IT(uint8_t speed)
References hi2c1.
void EVERT_EMC230X_SetFanSpeed_IT(const EVERT_EMC230X_Fan fan, uint8_t speed)
References EMC230X_REG_FAN1_SETTING, EVERT_EMC230X_FAN1, hi2c1.
void EVERT_EMC230X_SetRangeRegister_IT(const uint8_t range)
Referenced by EVERT_EMC230X_Init.
void EVERT_EMC230X_SetRxAction(const EVERT_EMC230X_RxAction action)
Referenced by EVERT_EMC230X_Init, EVERT_EMC230X_ReadTachs_IT.
void EVERT_EMC230X_SetTxAction(const EVERT_EMC230X_TxAction action)
Referenced by EVERT_EMC230X_Init.
void EVERT_EMC230X_ReadTachs_IT()
References EMC230X_ADDRESS, EMC230X_REG_FAN1_TACH_HIGH, EVERT_EMC230X_RX_ACTION_READ_TACHS_FAN1_HIGH, EVERT_EMC230X_SetRxAction, hi2c1.
void EVERT_EMC230X_OnErrorReceived()