inverter.c
TWO_PI
PHASE_OFFSET
Q31_MULTIPLIER
EVERT_INVERTER_ConfigCalibrationCurrentTypeDef calibration_current
Referenced by EVERT_INVERTER_ISR_HF_Readings.
EVERT_INVERTER_ConfigCalibrationTemperatureTypeDef calibration_temperature
Referenced by EVERT_INVERTER_ISR_HF_Readings, EVERT_INVERTER_ISR_LF_Readings.
EVERT_INVERTER_ConfigCalibrationVoltageBusTypeDef calibration_voltage_bus
Referenced by EVERT_INVERTER_ISR_HF_Readings.
EVERT_INVERTER_ConfigCalibrationVoltageGridTypeDef calibration_voltage_grid
Referenced by EVERT_INVERTER_ISR_HF_Readings.
EVERT_INVERTER_ConfigCalibrationVoltageTypeDef calibration_voltage
Referenced by EVERT_INVERTER_ISR_HF_Readings.
EVERT_INVERTER_ConfigConstraintsCurrentTypeDef constraints_current
EVERT_INVERTER_ConfigConstraintsDcBusTypeDef constraints_dc_bus
EVERT_INVERTER_ConfigConstraintsTemperatureFilterTypeDef constraints_temperature_filter
EVERT_INVERTER_ConfigConstraintsTemperatureHeatsinkTypeDef constraints_temperature_heatsink
EVERT_INVERTER_ConfigConstraintsVoltageTypeDef constraints_voltage
EVERT_INVERTER_TimeTypeDef time
Referenced by EVERT_INVERTER_loop.
EVERT_INVERTER_IoStateTypeDef io_state
ADC_HandleTypeDef hadc1
Referenced by HAL_ADC_ConvCpltCallback.
ADC_HandleTypeDef hadc2
ADC_HandleTypeDef hadc3
DMA_HandleTypeDef hdma_adc1
Referenced by EVERT_INVERTER_main.
DMA_HandleTypeDef hdma_adc2
Referenced by EVERT_INVERTER_main.
DMA_HandleTypeDef hdma_adc3
Referenced by EVERT_INVERTER_main.
HRTIM_HandleTypeDef hhrtim1
Referenced by EVERT_INVERTER_SetDeadtime, EVERT_INVERTER_SetDutyCycle, EVERT_INVERTER_SetPwmEnabled.
TIM_HandleTypeDef htim2
TIM_HandleTypeDef htim3
TIM_HandleTypeDef htim6
EVERT_HAL_GpioDefinitionTypeDef EVERT_INVERTER_GPIO_DEF_PWM_ENABLE
Referenced by EVERT_INVERTER_SetPwmEnabled.
EVERT_HAL_GpioDefinitionTypeDef EVERT_INVERTER_GPIO_DEF_PWM_RESET
Referenced by EVERT_INVERTER_SetPwmEnabled.
EVERT_HAL_GpioDefinitionTypeDef EVERT_INVERTER_GPIO_DEF_PWM_READY_TOP1
EVERT_HAL_GpioDefinitionTypeDef EVERT_INVERTER_GPIO_DEF_PWM_READY_TOP2
EVERT_HAL_GpioDefinitionTypeDef EVERT_INVERTER_GPIO_DEF_PWM_READY_TOP3
EVERT_HAL_GpioDefinitionTypeDef EVERT_INVERTER_GPIO_DEF_PWM_READY_BOT1
EVERT_HAL_GpioDefinitionTypeDef EVERT_INVERTER_GPIO_DEF_PWM_READY_BOT2
EVERT_HAL_GpioDefinitionTypeDef EVERT_INVERTER_GPIO_DEF_PWM_READY_BOT3
EVERT_HAL_GpioDefinitionTypeDef EVERT_INVERTER_GPIO_DEF_PWM_FAULT
EVERT_HAL_GpioDefinitionTypeDef EVERT_INVERTER_GPIO_DEF_PWM_FAN_FAULT
EVERT_HAL_GpioDefinitionTypeDef EVERT_INVERTER_GPIO_DEF_PWM_FDCAN_FAULT
volatile bool adc_completed[3][3]
int EVERT_INVERTER_main()
Device Emergency Shutdown Alarms.
Device Non-Operational Alarms Device Operational Warning Alarms
References HAL_DMA_ErrorCallback, hdma_adc1, hdma_adc2, hdma_adc3.
void EVERT_INVERTER_loop()
References EVERT_INVERTER_TimeTypeDef::current_time, EVERT_INVERTER_TimeTypeDef::delta_time, EVERT_INVERTER_TimeTypeDef::elapsed_time, EVERT_DEVICE_Update, EVERT_INVERTER_TimeTypeDef::last_time, EVERT_INVERTER_TimeTypeDef::start_time, time.
void GetDutyCycles(float32_t *duty_u, float32_t *duty_v, float32_t *duty_w)
References gf_duty_cycle_a_pu, gf_duty_cycle_b_pu, gf_duty_cycle_c_pu, PHASE_OFFSET, TWO_PI.
float32_t EVERT_INVERTER_GetDutyCycleCcrByPercentage(const float32_t percentage)
References EVERT_CONSTANT_INVERTER_PWM_PERIOD.
void EVERT_INVERTER_SetDeadtime(const uint32_t timer_index, uint16_t deadtime)
References EVERT_INVERTER_hal_error, hhrtim1.
void EVERT_INVERTER_SetDutyCycle(const float32_t duty_cycle_u, const float32_t duty_cycle_v, const float32_t duty_cycle_w)
References hhrtim1.
void EVERT_INVERTER_SetPwmEnabled(const bool enabled)
References EVERT_INVERTER_GPIO_DEF_PWM_ENABLE, EVERT_INVERTER_GPIO_DEF_PWM_RESET, hhrtim1, EVERT_HAL_GpioDefinitionTypeDef::pin, EVERT_HAL_GpioDefinitionTypeDef::port.
void EVERT_INVERTER_SetStatusLed(const uint8_t index, const uint32_t color, const uint32_t time_on, const uint32_t time_off)
Referenced by EVERT_DEVICE_Derived_OnDeviceStateChange, EVERT_INVERTER_CommonErrorCallback.
void __overrides EVERT_DEVICE_Derived_OnDeviceStateChange(const EVERT_DEVICE_StateTypeDef new_state, const EVERT_DEVICE_StateTypeDef old_state)
References DS_BOOTING, DS_EMERGENCY_SHUTDOWN, DS_OPERATIONAL, DS_OPERATIONAL_WARNING, EVERT_CONSTANT_INVERTER_STATUS_LED0_COLOR_BOOTING, EVERT_CONSTANT_INVERTER_STATUS_LED0_COLOR_ERROR, EVERT_CONSTANT_INVERTER_STATUS_LED0_COLOR_OK, EVERT_CONSTANT_INVERTER_STATUS_LED0_COLOR_WARNING, EVERT_CONSTANT_INVERTER_STATUS_LED0_TIME_BOOTING_OFF, EVERT_CONSTANT_INVERTER_STATUS_LED0_TIME_BOOTING_ON, EVERT_CONSTANT_INVERTER_STATUS_LED0_TIME_ERROR_OFF, EVERT_CONSTANT_INVERTER_STATUS_LED0_TIME_ERROR_ON, EVERT_CONSTANT_INVERTER_STATUS_LED0_TIME_OK_OFF, EVERT_CONSTANT_INVERTER_STATUS_LED0_TIME_OK_ON, EVERT_CONSTANT_INVERTER_STATUS_LED0_TIME_WARNING_OFF, EVERT_CONSTANT_INVERTER_STATUS_LED0_TIME_WARNING_ON, EVERT_CONSTANT_INVERTER_STATUS_LED1_COLOR_BOOTING, EVERT_CONSTANT_INVERTER_STATUS_LED1_COLOR_ERROR, EVERT_CONSTANT_INVERTER_STATUS_LED1_COLOR_OK, EVERT_CONSTANT_INVERTER_STATUS_LED1_COLOR_WARNING, EVERT_CONSTANT_INVERTER_STATUS_LED1_TIME_BOOTING_OFF, EVERT_CONSTANT_INVERTER_STATUS_LED1_TIME_BOOTING_ON, EVERT_CONSTANT_INVERTER_STATUS_LED1_TIME_ERROR_OFF, EVERT_CONSTANT_INVERTER_STATUS_LED1_TIME_ERROR_ON, EVERT_CONSTANT_INVERTER_STATUS_LED1_TIME_OK_OFF, EVERT_CONSTANT_INVERTER_STATUS_LED1_TIME_OK_ON, EVERT_CONSTANT_INVERTER_STATUS_LED1_TIME_WARNING_OFF, EVERT_CONSTANT_INVERTER_STATUS_LED1_TIME_WARNING_ON, EVERT_INVERTER_SetStatusLed.
void __overrides EVERT_DEVICE_Derived_OnEnterState_BootingComms()
References DS_BOOTING_DONE, EVERT_DEVICE_State_Set, SS_INTERNAL.
void __overrides EVERT_TASK_SCHEDULER_OnTaskSendAnnouncement(void)
void __overrides EVERT_TASK_SCHEDULER_OnTaskSendData(void)
void __overrides EVERT_TASK_SCHEDULER_OnTaskSendDeviceStatus(void)
void __overrides EVERT_TASK_SCHEDULER_OnTaskSendPing(void)
void EVERT_INVERTER_ISR_25KHZ_IRQHandler()
void EVERT_INVERTER_ISR_100HZ_IRQHandler()
void __overrides HAL_ADC_ConvCpltCallback(ADC_HandleTypeDef *hadc)
References hadc1.
void EVERT_INVERTER_hal_error(char *error_message)
References EVERT_INVERTER_CommonErrorCallback.
Referenced by EVERT_INVERTER_SetDeadtime.
void HAL_ADC_ErrorCallback(ADC_HandleTypeDef *hadc)
References EVERT_INVERTER_CommonErrorCallback.
void HAL_DMA_ErrorCallback(DMA_HandleTypeDef *hdma)
References EVERT_INVERTER_CommonErrorCallback.
Referenced by EVERT_INVERTER_main.
void HAL_FDCAN_ErrorCallback(FDCAN_HandleTypeDef *hfdcan)
References EVERT_INVERTER_CommonErrorCallback.
void HAL_FLASH_OperationErrorCallback(uint32_t ReturnValue)
References EVERT_INVERTER_CommonErrorCallback.
void HAL_I2C_ErrorCallback(I2C_HandleTypeDef *hi2c)
References EVERT_INVERTER_CommonErrorCallback.
void HAL_TIM_ErrorCallback(TIM_HandleTypeDef *htim)
References EVERT_INVERTER_CommonErrorCallback.
void EVERT_INVERTER_CommonErrorCallback(char *error_message)
References EVERT_CONSTANT_INVERTER_STATUS_LED0_COLOR_ERROR, EVERT_CONSTANT_INVERTER_STATUS_LED0_TIME_ERROR_OFF, EVERT_CONSTANT_INVERTER_STATUS_LED0_TIME_ERROR_ON, EVERT_CONSTANT_INVERTER_STATUS_LED1_COLOR_ERROR, EVERT_CONSTANT_INVERTER_STATUS_LED1_TIME_ERROR_OFF, EVERT_CONSTANT_INVERTER_STATUS_LED1_TIME_ERROR_ON, EVERT_HAL_BreakPoint, EVERT_INVERTER_SetStatusLed.
Referenced by EVERT_INVERTER_hal_error, HAL_ADC_ErrorCallback, HAL_DMA_ErrorCallback, HAL_FDCAN_ErrorCallback, HAL_FLASH_OperationErrorCallback, HAL_I2C_ErrorCallback, HAL_TIM_ErrorCallback.