boost_converter.c
EVERT_CONSTRAINT_CAN_BUFFER_SIZE
EVERT_BOOST_CONVERTER_ConfigCurrentCalibrationTypeDef calibration_current
Referenced by EVERT_BOOST_CONVERTER_Readings.
EVERT_BOOST_CONVERTER_ConfigVoltageCalibrationTypeDef calibration_voltage
Referenced by EVERT_BOOST_CONVERTER_Readings.
EVERT_BOOST_CONVERTER_ConfigCurrentConstraintsTypeDef constraints_current
EVERT_BOOST_CONVERTER_ConfigTemperatureConstraintsTypeDef constraints_temperature
EVERT_BOOST_CONVERTER_ConfigVoltageConstraintsTypeDef constraints_voltage
EVERT_HAL_GpioDefinitionTypeDef EVERT_BOOST_CONVERTER_GPIO_DEF_ID_SELECTION
Referenced by EVERT_BOOST_CONVERTER_main.
EVERT_BOOST_CONVERTER_TimeTypeDef time
Referenced by EVERT_BOOST_CONVERTER_loop, EVERT_BOOST_CONVERTER_main.
EVERT_BOOST_CONVERTER_IoStateTypeDef io_state
Referenced by EVERT_BOOST_CONVERTER_main.
volatile EVERT_BOOST_CONVERTER_MpptStateTypeDef mppt_state
Referenced by EVERT_BOOST_CONVERTER_AlarmChangedState, EVERT_BOOST_CONVERTER_MpptInit, EVERT_BOOST_CONVERTER_MpptRun, EVERT_BOOST_CONVERTER_SetDutyCycle, EVERT_CAN_OnMessageReceived.
EVERT_CAN_HandlerTypeDef can_handler
Referenced by EVERT_BOOST_CONVERTER_loop, EVERT_INVERTER_FDCAN_RxFifo0Callback, EVERT_TASK_SCHEDULER_OnTaskSendPing.
EVERT_CAN_FifoBufferItemTypeDef rx_fifo_items[EVERT_CONSTRAINT_CAN_BUFFER_SIZE][EVERT_CONSTRAINT_CAN_BUFFER_SIZE]
EVERT_CAN_FifoBufferItemTypeDef tx_fifo_items[EVERT_CONSTRAINT_CAN_BUFFER_SIZE][EVERT_CONSTRAINT_CAN_BUFFER_SIZE]
ADC_HandleTypeDef hadc1
Referenced by HAL_ADC_ConvCpltCallback.
DMA_HandleTypeDef hdma_adc1
Referenced by EVERT_BOOST_CONVERTER_main.
FDCAN_HandleTypeDef hfdcan1
HRTIM_HandleTypeDef hhrtim1
Referenced by EVERT_BOOST_CONVERTER_SetDutyCycle.
TIM_HandleTypeDef htim2
TIM_HandleTypeDef htim3
volatile bool adc_completed[1][1]
int EVERT_BOOST_CONVERTER_main()
Main function for the boost converter.
Initializes the boost converter and starts the main loop 0 if successful
References EVERT_BOOST_CONVERTER_GPIO_DEF_ID_SELECTION, HAL_DMA_ErrorCallback, hdma_adc1, EVERT_BOOST_CONVERTER_IoStateTypeDef::id_selection, io_state, EVERT_BOOST_CONVERTER_TimeTypeDef::start_time, time.
void EVERT_BOOST_CONVERTER_loop()
Main loop for the boost converter.
Runs the main loop for the boost converter
References can_handler, EVERT_BOOST_CONVERTER_TimeTypeDef::current_time, EVERT_BOOST_CONVERTER_TimeTypeDef::delta_time, EVERT_BOOST_CONVERTER_TimeTypeDef::elapsed_time, EVERT_BOOST_CONVERTER_TimeTypeDef::last_time, EVERT_BOOST_CONVERTER_TimeTypeDef::start_time, time.
void EVERT_BOOST_CONVERTER_SetDutyCycle(float32_t duty_cycle)
References EVERT_BOOST_CONVERTER_MpptStateTypeDef::duty_cycle, EVERT_CONSTRAINT_BC_DUTY_CYCLE_MAX, EVERT_CONSTRAINT_BC_DUTY_CYCLE_MIN, hhrtim1, mppt_state.
Referenced by EVERT_BOOST_CONVERTER_MpptInit, EVERT_BOOST_CONVERTER_MpptRun.
void __overrides EVERT_BOOST_CONVERTER_AlarmChangedState(EVERT_BOOST_CONVERTER_AlarmIndexTypeDef alarm_index, bool is_set)
References alarm_register, BCS_RUNNING, mppt_state, EVERT_BOOST_CONVERTER_MpptStateTypeDef::status.
void __overrides EVERT_CAN_OnMessageReceived(EVERT_CAN_HandlerTypeDef *handler, const EVERT_CAN_FrameTypeDef frame)
References BCS_RUNNING, BCS_STANDBY, mppt_state, EVERT_BOOST_CONVERTER_MpptStateTypeDef::status.
void __overrides EVERT_CAN_OnErrorReceived(EVERT_CAN_HandlerTypeDef *handler)
void __overrides EVERT_DEVICE_Derived_OnDeviceStateChange(const EVERT_DEVICE_StateTypeDef new_state, const EVERT_DEVICE_StateTypeDef old_state)
void __overrides EVERT_DEVICE_Derived_OnEnterState_BootingComms()
void __overrides EVERT_TASK_SCHEDULER_OnTaskSendAnnouncement(void)
void __overrides EVERT_TASK_SCHEDULER_OnTaskSendData(void)
void __overrides EVERT_TASK_SCHEDULER_OnTaskSendDeviceStatus(void)
void __overrides EVERT_TASK_SCHEDULER_OnTaskSendPing(void)
References can_handler.
void EVERT_BOOST_CONVERTER_ISR_10KHZ_IRQHandler()
void EVERT_BOOST_CONVERTER_ISR_100HZ_IRQHandler()
References EVERT_BOOST_CONVERTER_AlarmCheck, EVERT_BOOST_CONVERTER_MpptRun.
void __overrides HAL_ADC_ConvCpltCallback(ADC_HandleTypeDef *hadc)
References hadc1.
void __overrides EVERT_INVERTER_FDCAN_RxFifo0Callback(FDCAN_HandleTypeDef *hfdcan, uint32_t RxFifo0ITs)
References can_handler.
void EVERT_BOOST_CONVERTER_hal_error(char *error_message)
References EVERT_BOOST_CONVERTER_CommonErrorCallback.
void HAL_ADC_ErrorCallback(ADC_HandleTypeDef *hadc)
References EVERT_BOOST_CONVERTER_CommonErrorCallback.
void HAL_DMA_ErrorCallback(DMA_HandleTypeDef *hdma)
References EVERT_BOOST_CONVERTER_CommonErrorCallback.
Referenced by EVERT_BOOST_CONVERTER_main.
void HAL_FDCAN_ErrorCallback(FDCAN_HandleTypeDef *hfdcan)
References EVERT_BOOST_CONVERTER_CommonErrorCallback.
void HAL_FLASH_OperationErrorCallback(uint32_t ReturnValue)
References EVERT_BOOST_CONVERTER_CommonErrorCallback.
void HAL_I2C_ErrorCallback(I2C_HandleTypeDef *hi2c)
References EVERT_BOOST_CONVERTER_CommonErrorCallback.
void HAL_TIM_ErrorCallback(TIM_HandleTypeDef *htim)
References EVERT_BOOST_CONVERTER_CommonErrorCallback.
void EVERT_BOOST_CONVERTER_CommonErrorCallback(char *error_message)
Referenced by EVERT_BOOST_CONVERTER_hal_error, HAL_ADC_ErrorCallback, HAL_DMA_ErrorCallback, HAL_FDCAN_ErrorCallback, HAL_FLASH_OperationErrorCallback, HAL_I2C_ErrorCallback, HAL_TIM_ErrorCallback.