emc230x.c
EVERT_EMC230X_RxAction emc2303_rx_action
EVERT_EMC230X_TxAction emc2303_tx_action
EVERT_EMC230X_DataTypeDef emc230x_fan1
EVERT_EMC230X_DataTypeDef emc230x_fan2
EVERT_EMC230X_DataTypeDef emc230x_fan3
uint8_t emc2303_range_register
uint8_t emc2303_range_register_m
static uint16_t EVERT_EMC230X_CalculateRpm(uint16_t tach)
void EVERT_EMC230X_Init()
References EMC2303_REG_CONFIG_RANGE_1000, EVERT_EMC230X_RX_ACTION_NONE, EVERT_EMC230X_SetRangeRegister_IT, EVERT_EMC230X_SetRxAction, EVERT_EMC230X_SetTxAction, EVERT_EMC230X_TX_ACTION_NONE.
void EVERT_EMC230X_SetAllFanSpeeds_IT(uint8_t speed)
References hi2c1.
void EVERT_EMC230X_SetFanSpeed_IT(const EVERT_EMC230X_Fan fan, uint8_t speed)
References EMC230X_REG_FAN1_SETTING, EVERT_EMC230X_FAN1, hi2c1.
void EVERT_EMC230X_SetRangeRegister_IT(const uint8_t range)
Referenced by EVERT_EMC230X_Init.
void EVERT_EMC230X_SetRxAction(const EVERT_EMC230X_RxAction action)
Referenced by EVERT_EMC230X_Init, EVERT_EMC230X_ReadTachs_IT.
void EVERT_EMC230X_SetTxAction(const EVERT_EMC230X_TxAction action)
Referenced by EVERT_EMC230X_Init.
void EVERT_EMC230X_ReadTachs_IT()
References EMC230X_ADDRESS, EMC230X_REG_FAN1_TACH_HIGH, EVERT_EMC230X_RX_ACTION_READ_TACHS_FAN1_HIGH, EVERT_EMC230X_SetRxAction, hi2c1.
__weak void EVERT_EMC230X_OnErrorReceived()
void HAL_I2C_MemRxCpltCallback(I2C_HandleTypeDef *hi2c)
void HAL_I2C_MemTxCpltCallback(I2C_HandleTypeDef *hi2c)