status_register.c
void EVERT_SR_Init(EVERT_SR_RegisterTypeDefinitionTypeDef *status_reg)
References EVERT_SR_RegisterTypeDefinitionTypeDef::reg.
Referenced by EVERT_BOOST_CONVERTER_InitAlarmRegister.
uint32_t EVERT_SR_GetRegister(const EVERT_SR_RegisterTypeDefinitionTypeDef *status_reg)
References EVERT_SR_RegisterTypeDefinitionTypeDef::reg.
uint8_t EVERT_SR_GetBitOnCount(const EVERT_SR_RegisterTypeDefinitionTypeDef *status_reg)
References EVERT_SR_RegisterTypeDefinitionTypeDef::reg.
Referenced by EVERT_BOOST_CONVERTER_AlarmChangedState.
bool EVERT_SR_SetBit(EVERT_SR_RegisterTypeDefinitionTypeDef *status_reg, uint8_t index)
References EVERT_SR_RegisterTypeDefinitionTypeDef::reg.
bool EVERT_SR_ClearBit(EVERT_SR_RegisterTypeDefinitionTypeDef *status_reg, uint8_t index)
References EVERT_SR_RegisterTypeDefinitionTypeDef::reg.
bool EVERT_SR_IsBitSet(const EVERT_SR_RegisterTypeDefinitionTypeDef *status_reg, uint8_t index)
References EVERT_SR_RegisterTypeDefinitionTypeDef::reg.
Referenced by EVERT_SR_IsAnyBitSet.
bool EVERT_SR_IsAnyBitSet(const EVERT_SR_RegisterTypeDefinitionTypeDef *status_reg, const uint8_t *indexes, const uint8_t size)
References EVERT_SR_IsBitSet.
Referenced by EVERT_BOOST_CONVERTER_AlarmChangedState, EVERT_DEVICE_Alarm_Check.